config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
 end
  devise_for :users, :skip => :registration
  root to: "home#index"
  resources :estudiantes
  resources :docentes
  resources :cursos
  get '*any', via: :all, to: 'application#catch_404'
end

app/models/docente.rb
class Docente < ApplicationRecord
  has_many :cursos_docentes
  has_many :cursos, through: :cursos_docentes
  belongs_to :tipo_documento
  belongs_to :genero
end

app/controllers/docentes_controller.rb
class DocentesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_docente, only: %i[ show edit update destroy ]

  # GET /docentes or /docentes.json
  def index
    @docentes = Docente.all
  end

  # GET /docentes/1 or /docentes/1.json
  def show
  end

  # GET /docentes/new
  def new
    @docente = Docente.new
  end

  # GET /docentes/1/edit
  def edit
  end

  # POST /docentes or /docentes.json
  def create
    @docente = Docente.new(docente_params)

    respond_to do |format|
      if @docente.save
        format.html { redirect_to @docente, notice: "Docente was successfully created." }
        format.json { render :show, status: :created, location: @docente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docentes/1 or /docentes/1.json
  def update
    respond_to do |format|
      if @docente.update(docente_params)
        format.html { redirect_to @docente, notice: "Docente was successfully updated." }
        format.json { render :show, status: :ok, location: @docente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docentes/1 or /docentes/1.json
  def destroy
    @docente.destroy
    respond_to do |format|
      format.html { redirect_to docentes_url, notice: "Docente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docente
      @docente = Docente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def docente_params
      params.require(:docente).permit(:tipo_documento_id,:identificacion, :nombres, :apellidos, :genero_id, curso_ids:[])
    end
end

app/helpers/docentes_helper.rb
module DocentesHelper
end

app/views/docentes/_form.html.erb
<div class="container">
  <div class = "row">
      <div class="col-md-12">
        <%= simple_form_for(@docente) do |f| %>
          <% @docente.errors.full_messages.each do |message| %>
            <div class="form-group text-center be-red white">
            <%= message %>
            </div>
          <%end%>

          <div class="row">
            <div class="col-md-6">
              <%= f.input :nombres, required: true,
                  autofocus: true, class:"form-control", placeholder: "Digite su Nombre"%>
            </div>
            <div class="col-md-6">
              <%= f.input :apellidos, required: true,autofocus: true, min:1,
              class: 'form-control', placeholder: "Digite sus apellidos"%>
            </div>
          </div>
            <br>

        <div class="row">
              <div class="col-md-4">
                <%= f.association :tipo_documento, label_method: :nombre, value_method: :id, min:"1"%>
            </div>
            <div class="col-md-4">
                  <%= f.input :identificacion, required: true, autofocus: true, min:1, class:"form-control", placeholder: "Digite su numero de Identificacion"%>
            </div>
            <div class="col-md-4">
              <%= f.association :genero, label_method: :nombre, value_method: :id, min:"1"%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="col-md-4">
              <div class="form-check">
                  <h1>Cursos</h1>
                    <%= f.collection_check_boxes :curso_ids, Curso.all, :id, :nombre %>
               </div>
            </div>
          </div>
        </div>
          <div class="row">
          <div class="col-md-6">
            <%= f.submit "Registrar Docente", class:"btn btn-success" %>
          </div>
          </div>


  </div>

        <%end%>
      </div>

app/views/docentes/edit.html.erb
<h1>Editar Docente</h1>

<%= render 'form', docentes: @docente %>

<br>
<div class="row">
  <div class="col-md-6">
    <%= link_to 'Back', docentes_path, class: "btn btn-outline-warning" %>
  </div>
</div>

app/views/docentes/index.html.erb
<div class="container">
      <div class="table-responsive">
        <h1 class="text-center">Docentes</h1>
            <table class="table table-striped">
              <tr>
                <th class="active">Tipo de documento</th>
                <th class="active">Nombres</th>
                <th class="active">Apellidos</th>
                <th class="active">Identificacion</th>
                <th class="active">Genero</th>
                <th class="active">Cursos Asignados</th>
                <th class="active">ver</th>
                <th class="active">Editar</th>
                <th class="active">Eliminar</th>
              </tr>
              <div id="docentes" data-target="search.docentes">
                <% @docentes.each do |docente| %>
                  <tr>
                    <td><%=docente.tipo_documento.nombre%></td>
                    <td><%=docente.identificacion%></td>
                    <td><%=docente.nombres%></td>
                    <td><%=docente.apellidos%></td>
                    <td><%=docente.genero.nombre%></td>
                    <td><%=docente.cursos.count%></td>
                    <td><%= link_to "ver", docente_path(docente.id), class: "btn btn-outline-success" %></td>
                    <td><%= link_to "Editar", edit_docente_path(docente.id), class: "btn btn-outline-warning" %></td>
                    <td><%= link_to 'Eliminar', { :action => :destroy, :id => docente.id }, :method => :delete, :data => { :confirm => 'Desea eliminar este docente?' }, class: "btn btn-outline-danger" %></td>
                  </tr>
                <% end %>
              </div>
            </table>
      </div>

<%= link_to "Registrar Docente", new_docente_path, class:"btn btn-outline-primary" %>

app/views/docentes/new.html.erb
<h1>Nuevo Docente</h1>

<%= render 'form', docente: @docente %>

<%= link_to 'Back', docentes_path %>

app/views/docentes/show.html.erb
<p id="notice"><%= notice %></p>
<div clas="row">
  <div class="col-12 p-0 mt-3">
    <!--title-->
    <div class="ibox-title">
      <h1 class="pl-4"><strong>Información del docente</strong></h1>
    </div>
    <!--Estudiante -->
    <div class="ibox-content">
      <div class="info col-12">
        <div class="card border-secondar">
          <div class="card-header d-flex justify-content-between">
            <div class="card-subtitle">
              <h4>Tipo de documento: <strong><%= @docente.tipo_documento.nombre%></strong></h4>
              <h4>Identificacion: <strong><%= @docente.identificacion%></strong></h4>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-body">
              <h4 class="card-subtile">Nombres:</h4>
              <p class="card-text">
                <%= @docente.nombres%>
              </p>
            </div>
            <div class="card-body">
              <h4 class="card-subtile">apellidos:</h4>
              <p class="card-text">
                <%= @docente.apellidos%>
              </p>
            </div>
            <% if @docente.cursos.exists? %>
            <div class="card-body">
              <h4 class="card-subtile">Cursos asignados:</h4>
              <p class="card-text">
                <table class="table table-striped">
                  <tr>
                    <th class="active">Id</th>
                    <th class="active">Codigo</th>
                    <th class="active">Nombre</th>
                    <th class="active">Fecha de inicio</th>
                    <th class="active">Fecha de fin</th>
                  </tr>
                  <% @docente.cursos.each do |curso| %>
                  <tr>
                    <td><%=curso.id%></td>
                    <td><%=curso.nombre%></td>
                    <td><%=curso.codigo%></td>
                    <td><%=curso.fecha_inicio%></td>
                    <td><%=curso.fecha_fin%></td>
                    <% end %>
                  </tr>
                </table>
              </p>
            </div>
            <% else %>
            <div class="card-body">
              <h4 class="card-subtile">Docentes asignados:</h4>
              <script type="text/javascript">
                  alert('no hay docentes asignados')
              </script>

              <h2>No hay docentes asignados</h2>
            </div>
            <% end %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!--botonera-->
      <div class="row d-flex">
        <%= link_to "volver", docentes_path, class: "btn btn-outline-primary bn-lg col-4" %>
        <%= link_to 'Editar', edit_docente_path(@docente), class: "btn btn-outline-primary bn-lg col-4"  %>
        <%= link_to 'nuevo docente', new_docente_path, class: "btn btn-outline-primary bn-lg col-4"  %>
      </div>
    </div>
  </div>
</div>