config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
 end
  devise_for :users, :skip => :registration
  root to: "home#index"
  resources :estudiantes
  resources :docentes
  resources :cursos
  get '*any', via: :all, to: 'application#catch_404'
end

app/models/curso.rb
class Curso < ApplicationRecord
  has_many :cursos_docentes
  has_many :docentes, through: :cursos_docentes
  has_many :cursos_estudiantes
  has_many :estudiantes, through: :cursos_estudiantes
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_curso, only: %i[ show edit update destroy ]

  # GET /cursos or /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1 or /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos or /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: "Curso was successfully created." }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1 or /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: "Curso was successfully updated." }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1 or /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: "Curso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curso_params
      params.require(:curso).permit(:codigo, :nombre, :fecha_inicio, :fecha_fin, :observaciones, docente_ids:[], estudiante_ids:[])
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<div class="container">
  <div class = "row">
      <div class="col-md-12">
        <%= simple_form_for(@curso) do |f| %>
          <% @curso.errors.full_messages.each do |message| %>
            <div class="form-group text-center be-red white">
            <%= message %>
            </div>
          <%end%>

          <div class="row">
            <div class="col-md-6">
              <%= f.input :codigo, required: true,
                  autofocus: true, class:"form-control", placeholder: "Digite el codigo del curso"%>
            </div>
            <div class="col-md-6">
              <%= f.input :nombre, required: true,autofocus: true, min:1,
              class: 'form-control', placeholder: "Digite el nombre del curso"%>
            </div>
          </div>
            <br>

        <div class="row">
              <div class="col-md-6">
                <%= f.input :fecha_inicio, required: true,
                    autofocus: true, class:"form-control", placeholder: "Digite su Nombre"%>
            </div>
            <div class="col-md-6">
              <%= f.input :fecha_fin, required: true,
                  autofocus: true, class:"form-control", placeholder: "Digite su Nombre"%>
            </div>
            <div class="col-md-6">
              <div class="form-check">
                  <h1>Docentes</h1>
                    <%= f.collection_check_boxes :docente_ids, Docente.all, :id, :nombres %>
               </div>
            </div>
            <div class="col-md-6">
              <div class="form-check">
                  <h1>Estudiantes</h1>
                    <%= f.collection_check_boxes :estudiante_ids, Estudiante.all, :id, :nombres %>
               </div>
            </div>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">observaciones</span>
        </div>
        <%= f.input :observaciones, label: false %>
      </div>
        </div>
          <div class="row">
            <div class="col-md-6">
              <%= f.submit "Registrar Curso", class:"btn btn-success" %>
            </div>
          </div
  </div>

        <%end%>
      </div>

app/views/cursos/edit.html.erb
<h1>Editar Curso</h1>

<%= render 'form', curso: @curso %>
<br>
<div class="row">
  <div class="col-md-6">
    <%= link_to 'Back', cursos_path, class: "btn btn-outline-warning" %>
  </div>
</div>

app/views/cursos/index.html.erb
<div class="container">
      <div class="table-responsive">
        <h1 class="text-center">Cursos Disponibles</h1>
            <table class="table table-striped">
              <tr>
                <th class="active">Codigo</th>
                <th class="active">Nombre</th>
                <th class="active">Fecha Inicio</th>
                <th class="active">Fecha fin</th>
                <th class="active">ver</th>
                <th class="active">Editar</th>
                <th class="active">Eliminar</th>
              </tr>
              <% @cursos.each do |curso| %>
              <tr>
                <td><%=curso.codigo%></td>
                <td><%=curso.nombre%></td>
                <td><%=curso.fecha_inicio%></td>
                <td><%=curso.fecha_fin%></td>
                <td><%= link_to "ver", curso_path(curso.id), class: "btn btn-outline-success" %></td>
                <td><%= link_to "Editar", edit_curso_path(curso.id), class: "btn btn-outline-warning" %></td>
                <td><%= link_to 'Eliminar', { :action => :destroy, :id => curso.id }, :method => :delete, :data => { :confirm => 'Desea eliminar este curso?' }, class: "btn btn-outline-danger" %></td>
                <% end %>
              </tr>
            </table>
      </div>

<%= link_to "Registrar Curso", new_curso_path, class:"btn btn-outline-primary" %>

app/views/cursos/new.html.erb
<h1>Nuevo Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Back', cursos_path %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>
<div clas="row">
  <div class="col-12 p-0 mt-3">
    <!--title-->
    <div class="ibox-title">
      <h1 class="pl-4"><strong>Información del curso</strong></h1>
    </div>
    <!--Estudiante -->
    <div class="ibox-content">
      <div class="info col-12">
        <div class="card border-secondar">
          <div class="card-header d-flex justify-content-between">
            <div class="card-subtitle">
              <h4>Codigo del curso: <strong><%= @curso.codigo%></strong></h4>
              <h4>Nombre del curso: <strong><%= @curso.nombre%></strong></h4>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-body">
              <h4 class="card-subtile">Fecha de inicio:</h4>
              <p class="card-text">
                <%= @curso.fecha_inicio%>
              </p>
            </div>
            <div class="card-body">
              <h4 class="card-subtile">Fecha de fin:</h4>
              <p class="card-text">
                <%= @curso.fecha_fin%>
              </p>
            </div>
            <div class="card-body">
              <h4 class="card-subtile">observaciones:</h4>
              <p class="card-text">
                <%= @curso.observaciones%>
              </p>
            </div>
          </div>
          <% if @curso.docentes.exists? %>
          <div class="card-body">
            <h4 class="card-subtile">Docentes asignados:</h4>
            <p class="card-text">
              <table class="table table-striped">
                <tr>
                  <th class="active">Tipo de documento</th>
                  <th class="active">identificacion</th>
                  <th class="active">nombres</th>
                  <th class="active">apellidos</th>
                </tr>
                <% @curso.docentes.each do |docente| %>
                <tr>
                  <td><%=docente.tipo_documento.nombre%></td>
                  <td><%=docente.identificacion%></td>
                  <td><%=docente.nombres%></td>
                  <td><%=docente.apellidos%></td>
                  <% end %>
                </tr>
              </table>
            </p>
          </div>
          <% else %>
          <div class="card-body">
            <h4 class="card-subtile">Docentes asignados:</h4>
            <script type="text/javascript">
                alert('no hay docentes asignados')
            </script>
            <h2>No hay docentes asignados</h2>
          </div>
          <% end %>
          <% if @curso.docentes.exists? %>
          <div class="card-body">
            <h4 class="card-subtile">Estudiantes asignados:</h4>
            <p class="card-text">
              <table class="table table-striped">
                <tr>
                  <th class="active">Tipo de documento</th>
                  <th class="active">identificacion</th>
                  <th class="active">nombres</th>
                  <th class="active">apellidos</th>
                </tr>
                <% @curso.estudiantes.each do |estudiante| %>
                <tr>
                  <td><%=estudiante.tipo_documento.nombre%></td>
                  <td><%=estudiante.identificacion%></td>
                  <td><%=estudiante.nombres%></td>
                  <td><%=estudiante.apellidos%></td>
                  <% end %>
                </tr>
              </table>
            </p>
          </div>
          <% else %>
          <div class="card-body">
            <h4 class="card-subtile">Estudiantes matriculados:</h4>
            <script type="text/javascript">
                alert('no hay estudiantes asignados')
            </script>
            <h2>No hay docentes asignados</h2>
          </div>
          <% end %>
        </div>
      </div>
      <!--botonera-->
      <div class="row d-flex">
        <%= link_to "volver", cursos_path, class: "btn btn-outline-primary bn-lg col-4" %>
        <%= link_to 'Editar', edit_curso_path(@curso), class: "btn btn-outline-primary bn-lg col-4"  %>
        <%= link_to 'nuevo curso', new_curso_path, class: "btn btn-outline-primary bn-lg col-4"  %>
      </div>
    </div>
  </div>
</div>