config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
 end
  devise_for :users, :skip => :registration
  root to: "home#index"
  resources :estudiantes
  resources :docentes
  resources :cursos
  get '*any', via: :all, to: 'application#catch_404'
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
  belongs_to :tipo_documento
  belongs_to :genero
  has_many :cursos_estudiantes
  has_many :cursos, through: :cursos_estudiantes
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_estudiante, only: %i[ show edit update destroy ]

  # GET /estudiantes or /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1 or /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes or /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: "Estudiante was successfully created." }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1 or /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: "Estudiante was successfully updated." }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1 or /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: "Estudiante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudiante_params
      params.require(:estudiante).permit(:tipo_documento_id, :identificacion, :nombres, :apellidos, :genero_id, curso_ids:[])
    end
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_form.html.erb
<div class="container">
  <div class = "row">
      <div class="col-md-12">
        <%= simple_form_for(@estudiante) do |f| %>
          <% @estudiante.errors.full_messages.each do |message| %>
            <div class="form-group text-center be-red white">
            <%= message %>
            </div>
          <%end%>

          <div class="row">
            <div class="col-md-6">
              <%= f.input :nombres, required: true,
                  autofocus: true, class:"form-control", placeholder: "Digite su Nombre"%>
            </div>
            <div class="col-md-6">
              <%= f.input :apellidos, required: true,autofocus: true, min:1,
              class: 'form-control', placeholder: "Digite sus apellidos"%>
            </div>
          </div>
            <br>

        <div class="row">
              <div class="col-md-4">
                <%= f.association :tipo_documento, label_method: :nombre, value_method: :id, min:"1"%>
            </div>
            <div class="col-md-4">
                  <%= f.input :identificacion, required: true, autofocus: true, min:1, class:"form-control", placeholder: "Digite su numero de Identificacion"%>
            </div>
            <div class="col-md-4">
              <%= f.association :genero, label_method: :nombre, value_method: :id, min:"1"%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="form-check">
                <h1>Cursos</h1>
                  <%= f.collection_check_boxes :curso_ids, Curso.all, :id, :nombre %>
             </div>
        </div>
          <div class="row">
          <div class="col-md-6">
            <%= f.submit "Registrar Estudiante", class:"btn btn-success" %>
          </div>
          </div>


  </div>

        <%end%>
      </div>

app/views/estudiantes/edit.html.erb
<h1>Editar Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<br>
<div class="row">
  <div class="col-md-6">
    <%= link_to 'Back', estudiantes_path, class: "btn btn-outline-warning" %>
  </div>
</div>

app/views/estudiantes/index.html.erb
<div class="container">
      <div class="table-responsive">
        <h1 class="text-center">Estudiantes</h1>
            <table class="table table-striped">
              <tr>
                <th class="active">Tipo de documento</th>
                <th class="active">Nombres</th>
                <th class="active">Apellidos</th>
                <th class="active">Identificacion</th>
                <th class="active">genero</th>
                <th class="active">cursos</th>
                <th class="active">ver</th>
                <th class="active">Editar</th>
                <th class="active">Eliminar</th>
              </tr>
              <% @estudiantes.each do |estudiante| %>
              <tr class="table-light">
                <td><%=estudiante.tipo_documento.nombre%></td>
                <td><%=estudiante.identificacion%></td>
                <td><%=estudiante.nombres%></td>
                <td><%=estudiante.apellidos%></td>
                <td><%=estudiante.genero.nombre%></td>
                <td><%=estudiante.cursos.count%></td>
                <td><%= link_to "ver", estudiante_path(estudiante.id), class: "btn btn-outline-success" %></td>
                <td><%= link_to "Editar", edit_estudiante_path(estudiante.id), class: "btn btn-outline-warning" %></td>
                <td><%= link_to 'Eliminar', { :action => :destroy, :id => estudiante.id }, :method => :delete, :data => { :confirm => 'Desea eliminar este estudiante?' }, class: "btn btn-outline-danger" %></td>
                <% end %>
              </tr>
            </table>
      </div>

<%= link_to "Registrar Estudiante", new_estudiante_path, class:"btn btn-outline-primary" %>

app/views/estudiantes/new.html.erb
<h1>Nuevo Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

  <%= link_to 'Atras', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>
<div clas="row">
  <div class="col-12 p-0 mt-3">
    <!--title-->
    <div class="ibox-title">
      <h1 class="pl-4"><strong>Información del estudiante</strong></h1>
    </div>
    <!--Estudiante -->
    <div class="ibox-content">
      <div class="info col-12">
        <div class="card border-secondar">
          <div class="card-header d-flex justify-content-between">
            <div class="card-subtitle">
              <h4>Tipo de documento: <strong><%= @estudiante.tipo_documento.nombre%></strong></h4>
              <h4>Identificacion: <strong><%= @estudiante.identificacion%></strong></h4>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card-body">
              <h4 class="card-subtile">Nombres:</h4>
              <p class="card-text">
                <%= @estudiante.nombres%>
              </p>
            </div>
            <div class="card-body">
              <h4 class="card-subtile">apellidos:</h4>
              <p class="card-text">
                <%= @estudiante.apellidos%>
              </p>
            </div>
            <% if @estudiante.cursos.exists? %>
            <div class="card-body">
              <h4 class="card-subtile">Cursos Activos:</h4>
              <p class="card-text">
                <table class="table table-striped">
                  <tr>
                    <th class="active">id</th>
                    <th class="active">Codigo</th>
                    <th class="active">Nombre</th>
                    <th class="active">fecha_inicio</th>
                    <th class="active">fecha_fin</th>
                  </tr>
                  <% @estudiante.cursos.each do |curso| %>
                  <tr>
                    <td><%=curso.id%></td>
                    <td><%=curso.codigo%></td>
                    <td><%=curso.nombre%></td>
                    <td><%=curso.fecha_inicio%></td>
                    <td><%=curso.fecha_fin%></td>
                    <% end %>
                  </tr>
                </table>
              </p>
            </div>
            <% else %>
            <div class="card-body">
              <h4 class="card-subtile">Cursos asignados:</h4>
              <script type="text/javascript">
                  alert('no tiene cursos matriculados')
              </script>

              <h2>no tiene cursos matriculados</h2>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <!--botonera-->
      <!--botonera-->
      <div class="row d-flex">
        <%= link_to "volver", estudiantes_path, class: "btn btn-outline-primary bn-lg col-4" %>
        <%= link_to 'Editar', edit_estudiante_path(@estudiante), class: "btn btn-outline-primary bn-lg col-4"  %>
        <%= link_to 'nuevo estudiante', new_estudiante_path, class: "btn btn-outline-primary bn-lg col-4"  %>
      </div>
    </div>
  </div>
</div>